// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeHBzdWF1dmxncmxuaWVwa2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDAxOTMsImV4cCI6MjA3MTc3NjE5M30.3UM9HvqGKH5XLj6wjJK3sBtBWbc7xQXb32-XqBtY80E"
const SUPABASE_URL="https://xcxpsuauvlgrlniepkdm.supabase.co"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});